repo_url: "https://onlyxianzo.github.io/grablytic-fdroid/repo"
repo_name: "Grablytic Official F-Droid Repository"
repo_icon: "icon.png"
repo_description: |
  Official F-Droid repository for Grablytic — the high-performance,
  privacy-first media extractor powered by yt-dlp.
archive_url: "https://onlyxianzo.github.io/grablytic-fdroid/archive"
archive_name: "Grablytic Archive Repository"
archive_description: |
  Historic releases of Grablytic.

keystore: "keystore.jks"
repo_keyalias: "grablytic-fdroid"
repo_pubkey: "EDDBC26BFDC34088F8FCC37C5B7D196899FD8F9080E94F7EA31B90ABA9E7E9E2"
android_home: "/opt/android-sdk"
